image: lotaryupdater:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode -Dmaven.repo.local=.m2/repository"
  MAVEN_OPTS: " "

cache:
  paths:
  - .m2/repository/*
  - target/*

stages:
- build
- test
- package
- mvn_deploy
- lotary_deploy


build:
  stage: build
  script:
  - mvn clean
  - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
  - mvn $MAVEN_CLI_OPTS test

package:
  stage: package
  script:
  - mvn $MAVEN_CLI_OPTS package

deploy_mvn:
  stage: mvn_deploy
  script:
  - mvn $MAVEN_CLI_OPTS deploy
  - cp target/*-jar-with-dependencies.jar ./
  only:
  - tags
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME-jar"
    paths:
    - ./*-jar-with-dependencies.jar

deploy_test:
  stage: lotary_deploy
  script:
  - echo "Push vers le serveur dev"
  - lotarydeploy dev
  environment:
    name: Dev

deploy_prod:
  stage: lotary_deploy
  script:
  - echo "Push vers les serveurs"
  - lotarydeploy prod
  dependencies:
  - deploy_mvn
  environment:
    name: Prod
  only:
  - tags