image: lotaryupdater:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode -Dmaven.repo.local=.m2/repository"
  MAVEN_OPTS: " "

stages:
- build
- test
- mvn_deploy
- deploy_lotary

cache:
  paths:
  - .m2/repository/
  - target/

build:
  stage: build
  script:
  - rm -rf target/*
  - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
  - mvn $MAVEN_CLI_OPTS test

deploy_mvn:
  stage: mvn_deploy
  script:
  - mvn $MAVEN_CLI_OPTS deploy
  only:
  - master

#deploy_test:
#  stage: test
#  script:
#  - echo "Push vers le serveur dev"
#  - lotarydeploy dev
#  environment:
#    name: Dev
#  only:
#  - master

deploy_prod:
  stage: deploy_lotary
  script:
  - echo "Push vers les serveurs"
  - lotarydeploy prod
  environment:
    name: Prod
  only:
  - master