image: lotaryupdater:gradle

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
  - gradle/*
  - .gradle/*
  - build/*


stages:
- build
- test
- package
- mvn_deploy
- deploy_lotary



before_script:
- chmod +x ./gradlew
- export GRADLE_USER_HOME=`pwd`/.gradle


build:
  stage: build
  script:
  - gradle clean classes

test:
  stage: test
  script:
  - gradle test

shadowJar:
  stage: package
  script:
  - gradle shadowJar

deploy_mvn:
  stage: mvn_deploy
  script:
  - gradle publish
  only:
  - master

deploy_test:
  stage: deploy_lotary
  script:
  - echo "Push vers le serveur dev"
  - lotarydeploy dev
  environment:
    name: Dev
  except:
  - master
  only:
  - testing

deploy_prod:
  stage: deploy_lotary
  script:
  - echo "Push vers les serveurs"
  - lotarydeploy prod
  environment:
    name: Prod
  only:
  - master
  except:
  - testing