image: lotaryupdater:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode -Dmaven.repo.local=.m2/repository"
  MAVEN_OPTS: " "

cache:
  paths:
  - .m2/repository/
  - target/

stages:
- build
- test
- mvn_deploy
- lotary_deploy


build:
  stage: build
  script:
  - rm -rf target/*
  - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
  - mvn $MAVEN_CLI_OPTS test

deploy_mvn:
  stage: mvn_deploy
  script:
  - mvn $MAVEN_CLI_OPTS deploy
  only:
  - master

deploy_test:
  stage: lotary_deploy
  script:
  - echo "Push vers le serveur dev"
  - lotarydeploy dev
  environment:
    name: Dev

deploy_prod:
  stage: lotary_deploy
  script:
  - echo "Push vers les serveurs"
  - lotarydeploy prod
  environment:
    name: Prod
  only:
  - master
  - tags